#**Task 2 : Concise Video Game Data Enhancement with Google AI Studio API**

## 1. SETUP

install library yang diperlukan seperti google-generativeai dan tqdm
1. google-generativeai
  digunakan untuk:
  - Mengakses model AI generatif Gemini dari Google
  - Mengirim prompt (teks perintah) ke model
  - Mendapatkan jawaban otomatis dari model AI
2. tqdm
  digunakan untuk: Menampilkan progress bar saat loop

In [2]:
pip install google-generativeai

Requirement already satisfied: google-generativeai in /usr/local/lib/python3.11/dist-packages (0.8.4)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.24.2)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.164.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.38.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (5.29.4)
Requirement already satisfied: pydantic in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (2.11.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (4.67.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.11/dist-packages (from google-generativeai) (4.13.1)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.11/dist-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.26.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core->google-generativeai) (1.69.2)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /usr/local/lib/python3.11/dist-packages (from google-api-core->google-generativeai) (2.32.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=2.15.0->google-generativeai) (4.9)
Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai) (0.22.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.11/dist-packages (from google-api-python-client->google-generativeai) (4.1.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.1 in /usr/local/lib/python3.11/dist-packages (from pydantic->google-generativeai) (2.33.1)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic->google-generativeai) (0.4.0)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.0)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /usr/local/lib/python3.11/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.0)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /usr/local/lib/python3.11/dist-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.3)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2025.1.31)

In [3]:
!pip install -q tqdm

## 2. Google API Key

- Mengimpor library getpass untuk meminta pengguna untuk memasukkan API key tanpa ditampilkan agar aman saat script ini dibagikan. Karena API key tidak boleh dishare ke orang lain karena berisi data dari pengguna
- Mengimpor library resmi Google Gemini API (google-generativeai) untuk mengatur konfigurasi API key agar bisa memakai layanan Gemini.

In [1]:
import getpass
import google.generativeai as genai

# Minta pengguna memasukkan API key tanpa ditampilkan
API_KEY = getpass.getpass("Masukkan API Key dari https://aistudio.google.com/app/apikey: ")

# Konfigurasi Gemini API
genai.configure(api_key=API_KEY)

Masukkan API Key dari https://aistudio.google.com/app/apikey: ··········

##3. READ DATA

Mengupload datset yang digunakan menggunakan library files dari google colab dan membaca data dengan library pandas

In [2]:
from google.colab import files

# Upload file CSV, misalnya: game_data.csv
uploaded = files.upload()

Saving Game Thumbnail.csv to Game Thumbnail.csv

In [3]:
import pandas as pd

# Ganti nama file sesuai file yang kamu upload
df = pd.read_csv("Game Thumbnail.csv")

# Lihat 5 baris pertama untuk konfirmasi
df.head()

            game_title                                          image_url
0     Street Fighter 6  https://images.igdb.com/igdb/image/upload/t_co...
1  Hunt: Showdown 1896  https://images.igdb.com/igdb/image/upload/t_co...
2      Wuthering Waves  https://images.igdb.com/igdb/image/upload/t_co...
3        Arma Reforger  https://images.igdb.com/igdb/image/upload/t_co...
4       Lethal Company  https://images.igdb.com/igdb/image/upload/t_co...

## 4. Menambahkan kolom dan mengisi kolom dengan menggunakan hasil prompt dari gemini

Membuat fungsi generate_text() yang digunakan untuk mengirim prompt ke model AI Google Gemini dan mengembalikan hasil teks dari AI tersebut. Fungsi ini dilengkapi dengan mekanisme retry otomatis untuk mengantisipasi kegagalan saat memanggil API. Di dalamnya, model gemini-2.0-flash-lite digunakan karena versi ini ringan dan cepat. Jika permintaan gagal, fungsi akan mencoba ulang hingga tiga kali dengan jeda dua detik antar percobaan. Jika semua percobaan gagal, fungsi akan mengembalikan nilai "N/A". Dengan pendekatan ini, fungsi generate_text() menjadi lebih stabil dan tahan terhadap gangguan jaringan atau pembatasan sementara dari API.

In [4]:
import time
import re
from tqdm import tqdm

def generate_text(prompt, retries=3, delay=2):
    for attempt in range(retries):
        try:
            model = genai.GenerativeModel("gemini-2.0-flash-lite")
            response = model.generate_content(prompt)
            return response.text.strip()
        except Exception as e:
            print(f"Attempt {attempt + 1} failed: {e}")
            time.sleep(delay)
    return "N/A"

### 4.1 Kolom Genre

Melakukan proses pengambilan genre utama dari setiap judul game dalam DataFrame df. Pertama, genre_list diinisialisasi sebagai list kosong untuk menyimpan hasil. Lalu, dengan bantuan tqdm, dilakukan iterasi untuk menampilkan progress bar saat memproses kolom game_title. Untuk setiap judul game (title), dibentuk sebuah prompt yang meminta AI menyebutkan genre utama dalam satu kata, contohnya seperti "Aksi", "Shooter", atau "Strategi". Prompt ini dikirim ke fungsi generate_text() yang akan mengembalikan respons dari model AI. Kemudian hasil mentah (genre_raw) dibersihkan menggunakan regular expression re.findall(r'\w+', genre_raw), yang akan mengekstrak hanya huruf dan angka (menghilangkan karakter spesial atau tanda baca). Jika hasil bersih (genre_clean) ada isinya, maka hanya kata pertama yang diambil sebagai genre, jika tidak ada, maka akan diisi dengan string default "Lainnya". Genre akhir ini lalu ditambahkan ke dalam genre_list.

In [5]:
genre_list = []

for title in tqdm(df["game_title"]):
    prompt_genre = (
        f"Apa genre utama dari video game berjudul '{title}'? "
        f"Jawab dengan satu kata saja seperti: Aksi, Petualangan, Shooter, Strategi, dll."
    )

    genre_raw = generate_text(prompt_genre)
    genre_clean = re.findall(r'\w+', genre_raw)
    genre = genre_clean[0] if genre_clean else "Lainnya"
    genre_list.append(genre)

 10%|█         | 5/50 [00:21<02:17,  3.05s/it]ERROR:tornado.access:500 POST /v1beta/models/gemini-2.0-flash-lite:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 13960.23ms

Attempt 1 failed: 500 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent?%24alt=json%3Benum-encoding%3Dint: TypeError: Failed to fetch

 16%|█▌        | 8/50 [00:42<03:09,  4.51s/it]ERROR:tornado.access:500 POST /v1beta/models/gemini-2.0-flash-lite:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 12347.75ms

Attempt 1 failed: 500 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent?%24alt=json%3Benum-encoding%3Dint: TypeError: Failed to fetch

100%|██████████| 50/50 [04:10<00:00,  5.02s/it]

In [6]:
df["genre"] = genre_list

# Lihat hasilnya
df

,game_title,image_url,genre
0,Street Fighter 6,https://images.igdb.com/igdb/image/upload/t_co...,Pertarungan
1,Hunt: Showdown 1896,https://images.igdb.com/igdb/image/upload/t_co...,Shooter
2,Wuthering Waves,https://images.igdb.com/igdb/image/upload/t_co...,Aksi
3,Arma Reforger,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi
4,Lethal Company,https://images.igdb.com/igdb/image/upload/t_co...,Horor
5,Arena Breakout: Infinite,https://images.igdb.com/igdb/image/upload/t_co...,Shooter
6,Zenless Zone Zero,https://images.igdb.com/igdb/image/upload/t_co...,Aksi
7,ARK: Survival Ascended,https://images.igdb.com/igdb/image/upload/t_co...,Bertahan
8,Sid Meier's Civilization VII,https://images.igdb.com/igdb/image/upload/t_co...,Strategi
9,SMITE 2,https://images.igdb.com/igdb/image/upload/t_co...,MOBA
10,Throne and Liberty,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG
11,Enshrouded,https://images.igdb.com/igdb/image/upload/t_co...,Aksi
12,Poppy Playtime,https://images.igdb.com/igdb/image/upload/t_co...,Horor
13,It Takes Two,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan
14,DYNASTY WARRIORS: ORIGINS,https://images.igdb.com/igdb/image/upload/t_co...,Aksi
15,NHL 25,https://images.igdb.com/igdb/image/upload/t_co...,Olahraga
16,Balatro,https://images.igdb.com/igdb/image/upload/t_co...,Roguelike
17,MiSide,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan
18,Metaphor: ReFantazio,https://images.igdb.com/igdb/image/upload/t_co...,RPG
19,Indiana Jones and the Great Circle,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan
20,Hell Let Loose,https://images.igdb.com/igdb/image/upload/t_co...,Shooter
21,Super Mario 64,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan
22,S.T.A.L.K.E.R. 2: Heart of Chornobyl,https://images.igdb.com/igdb/image/upload/t_co...,Shooter
23,STALCRAFT: X,https://images.igdb.com/igdb/image/upload/t_co...,Shooter
24,Supermarket Together,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi
25,Ragnarok Online 2,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG
26,The Outlast Trials,https://images.igdb.com/igdb/image/upload/t_co...,Horor
27,Detroit: Become Human,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan
28,EA Sports UFC 2,https://images.igdb.com/igdb/image/upload/t_co...,Olahraga
29,Palia,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi
30,Green Hell,https://images.igdb.com/igdb/image/upload/t_co...,Survival
31,Microsoft Flight Simulator 2024,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi
32,Teamfight Tactics,https://images.igdb.com/igdb/image/upload/t_co...,Strategi
33,No Man's Sky,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan
34,Farming Simulator 25,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi
35,Tom Clancy's The Division 2,https://images.igdb.com/igdb/image/upload/t_co...,Shooter
36,Super Smash Bros. Ultimate,https://images.igdb.com/igdb/image/upload/t_co...,Pertarungan
37,Dying Light,https://images.igdb.com/igdb/image/upload/t_co...,Aksi
38,Sniper Elite: Resistance,https://images.igdb.com/igdb/image/upload/t_co...,Shooter
39,New World: Aeternum,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG
40,Hello Kitty Island Adventure,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan
41,The Headliners,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan
42,Mir Tankov,https://images.igdb.com/igdb/image/upload/t_co...,Strategi
43,The Binding of Isaac: Repentance,https://images.igdb.com/igdb/image/upload/t_co...,Roguelike
44,Exoborne,https://images.igdb.com/igdb/image/upload/t_co...,Shooter
45,Grand Theft Auto: San Andreas,https://images.igdb.com/igdb/image/upload/t_co...,Aksi
46,Infinity Nikki,https://images.igdb.com/igdb/image/upload/t_co...,Gaya
47,Borderlands 3,https://images.igdb.com/igdb/image/upload/t_co...,Shooter
48,Knight Online,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG
49,Supermarket Simulator,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi

### 4.2 Kolom Short Description

Pertama, dibuat list kosong bernama desc_list yang akan menyimpan hasil deskripsi tiap game. Lalu dilakukan iterasi terhadap kolom game_title menggunakan tqdm agar muncul progress bar. Untuk setiap title, disusun prompt yang meminta AI untuk membuat deskripsi singkat kurang dari 30 kata yang mencerminkan gameplay dan konsep utama dari game tersebut. Hasil dari prompt disimpan dalam desc_raw, lalu dibersihkan menggunakan re.findall(r'.{1,30}', desc_raw). Namun, perlu dicatat bahwa ekspresi ini justru memotong deskripsi setiap 30 karakter (bukan kata), yang mungkin tidak sesuai dengan maksud awal. Hasil potongan tersebut kemudian disatukan kembali menjadi satu string desc, atau diisi "Deskripsi tidak tersedia" jika kosong. Terakhir, deskripsi itu dimasukkan ke dalam desc_list.

In [7]:
desc_list = []

# Loop untuk setiap judul game dan mengambil deskripsi
for title in tqdm(df["game_title"]):
    # Prompt deskripsi singkat
    prompt_desc = (
        f"Tuliskan deskripsi singkat di bawah 30 kata untuk game berjudul '{title}'. "
        f"Pastikan deskripsi menggambarkan gameplay dan konsep utama dari game tersebut."
    )

    # Ambil hasil deskripsi
    desc_raw = generate_text(prompt_desc)
    desc_clean = re.findall(r'.{1,30}', desc_raw)  # ambil kata yang valid dan pastikan tidak lebih dari 30 kata
    desc = ' '.join(desc_clean) if desc_clean else "Deskripsi tidak tersedia"
    desc_list.append(desc)

  4%|▍         | 2/50 [00:48<21:18, 26.63s/it]ERROR:tornado.access:500 POST /v1beta/models/gemini-2.0-flash-lite:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 482.30ms

Attempt 1 failed: 500 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent?%24alt=json%3Benum-encoding%3Dint: TypeError: Failed to fetch

ERROR:tornado.access:500 POST /v1beta/models/gemini-2.0-flash-lite:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 31623.20ms

Attempt 2 failed: 500 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent?%24alt=json%3Benum-encoding%3Dint: TypeError: Failed to fetch

 26%|██▌       | 13/50 [02:27<06:13, 10.10s/it]ERROR:tornado.access:500 POST /v1beta/models/gemini-2.0-flash-lite:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 13986.33ms

Attempt 1 failed: 500 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent?%24alt=json%3Benum-encoding%3Dint: TypeError: Failed to fetch

 88%|████████▊ | 44/50 [06:11<00:37,  6.29s/it]ERROR:tornado.access:500 POST /v1beta/models/gemini-2.0-flash-lite:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 11234.79ms

Attempt 1 failed: 500 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent?%24alt=json%3Benum-encoding%3Dint: TypeError: Failed to fetch

100%|██████████| 50/50 [06:53<00:00,  8.27s/it]

In [8]:
df["short_description"] = desc_list

# Lihat hasilnya
df

,game_title,image_url,genre,short_description
0,Street Fighter 6,https://images.igdb.com/igdb/image/upload/t_co...,Pertarungan,Street Fighter 6: Pertarungan jalanan klasik ...
1,Hunt: Showdown 1896,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Berburu monster brutal dan pem ain lain dalam ...
2,Wuthering Waves,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,Wuthering Waves adalah RPG aks i dunia terbuka...
3,Arma Reforger,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,Arma Reforger adalah game simu lasi perang mul...
4,Lethal Company,https://images.igdb.com/igdb/image/upload/t_co...,Horor,Lethal Company adalah game hor or kooperatif t...
5,Arena Breakout: Infinite,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,"Masuki Arena Breakout: Infinit e, penembak FPS..."
6,Zenless Zone Zero,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,"""Zenless Zone Zero"" adalah gam e aksi RPG yang..."
7,ARK: Survival Ascended,https://images.igdb.com/igdb/image/upload/t_co...,Bertahan,Bertahan hidup di dunia purba yang liar! Kump...
8,Sid Meier's Civilization VII,https://images.igdb.com/igdb/image/upload/t_co...,Strategi,Raih kejayaan dalam Civilizati on VII! Bangun ...
9,SMITE 2,https://images.igdb.com/igdb/image/upload/t_co...,MOBA,SMITE 2 adalah MOBA dewa-dewi generasi beriku...
10,Throne and Liberty,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG,Jelajahi dunia terbuka yang lu as dalam **Thro...
11,Enshrouded,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,"Bangun, bertarung, dan jelajah i dunia yang di..."
12,Poppy Playtime,https://images.igdb.com/igdb/image/upload/t_co...,Horor,"Jelajahi pabrik mainan terbeng kalai, pecahkan..."
13,It Takes Two,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,Petualangan kooperatif yang me nakjubkan! Berm...
14,DYNASTY WARRIORS: ORIGINS,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,Kalahkan ribuan musuh dalam pe rtempuran besar...
15,NHL 25,https://images.igdb.com/igdb/image/upload/t_co...,Olahraga,NHL 25: Rasakan aksi hoki es y ang otentik! Ku...
16,Balatro,https://images.igdb.com/igdb/image/upload/t_co...,Roguelike,Balatro adalah deckbuilder rog uelike tentang ...
17,MiSide,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,MiSide adalah game simulasi ke hidupan santai ...
18,Metaphor: ReFantazio,https://images.igdb.com/igdb/image/upload/t_co...,RPG,"Bertualanglah dalam Metaphor: ReFantazio, seb..."
19,Indiana Jones and the Great Circle,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,"Sebagai Indiana Jones, pecahka n misteri kuno ..."
20,Hell Let Loose,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Hell Let Loose adalah game pen embak taktis Pe...
21,Super Mario 64,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,Petualangan 3D ikonik Mario! J elajahi dunia l...
22,S.T.A.L.K.E.R. 2: Heart of Chornobyl,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,"Bertahan hidup di Zona, dunia pasca-apokalipt..."
23,STALCRAFT: X,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,STALCRAFT: X adalah RPG bertah an hidup multip...
24,Supermarket Together,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,Supermarket Together: Bekerja sama dengan tem...
25,Ragnarok Online 2,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG,Ragnarok Online 2: Jelajahi du nia fantasi yan...
26,The Outlast Trials,https://images.igdb.com/igdb/image/upload/t_co...,Horor,The Outlast Trials adalah game horor survival...
27,Detroit: Become Human,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,"Dalam 'Detroit: Become Human', kendalikan and..."
28,EA Sports UFC 2,https://images.igdb.com/igdb/image/upload/t_co...,Olahraga,Rasakan kerasnya pertarungan M MA! EA Sports U...
29,Palia,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,Palia adalah MMO komunitas yan g nyaman. Berin...
30,Green Hell,https://images.igdb.com/igdb/image/upload/t_co...,Survival,Bertahan hidup di hutan Amazon yang kejam. Je...
31,Microsoft Flight Simulator 2024,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,Terbanglah di dunia yang detai l dalam Microso...
32,Teamfight Tactics,https://images.igdb.com/igdb/image/upload/t_co...,Strategi,Rakit tim juara dan lawan pema in lain dalam p...
33,No Man's Sky,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,Jelajahi alam semesta yang tak terbatas di No...
34,Farming Simulator 25,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,Kembangkan pertanian impianmu di Farming Simu...
35,Tom Clancy's The Division 2,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Bertahan hidup di Washington D .C. pasca-pande...
36,Super Smash Bros. Ultimate,https://images.igdb.com/igdb/image/upload/t_co...,Pertarungan,Bertarunglah dengan berbagai k arakter ikonik ...
37,Dying Light,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,Bertahan hidup di dunia pasca- apokaliptik yan...
38,Sniper Elite: Resistance,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Sniper Elite: Resistance adala h game stealth ...
39,New World: Aeternum,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG,Jelajahi dunia Aeternum yang m emukau! Bertaru...
40,Hello Kitty Island Adventure,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,Jelajahi Pulau yang dipenuhi t eman Sanrio! Ke...
41,The Headliners,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,Pimpin band rockmu menuju punc ak! Kelola angg...
42,Mir Tankov,https://images.igdb.com/igdb/image/upload/t_co...,Strategi,Mir Tankov adalah game aksi ta nk 3D intens. K...
43,The Binding of Isaac: Repentance,https://images.igdb.com/igdb/image/upload/t_co...,Roguelike,"""The Binding of Isaac: Repenta nce"" adalah *ro..."
44,Exoborne,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Exoborne adalah open-world ext raction shooter...
45,Grand Theft Auto: San Andreas,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,Jelajahi negara bagian San And reas yang luas ...
46,Infinity Nikki,https://images.igdb.com/igdb/image/upload/t_co...,Gaya,"Nikki memasuki dunia fantasi y ang luas, mengg..."
47,Borderlands 3,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Tembak dan rampas habis-habisa n! Jelajahi dun...
48,Knight Online,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG,"Bertarung dalam Knight Online, MMORPG epik! P..."
49,Supermarket Simulator,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,"Kelola supermarket impianmu! B eli produk, tat..."

### 4.3 Kolom Player Mode

Menambahkan kolom baru yang berisi informasi tentang mode permainan setiap game dalam DataFrame df. Untuk setiap judul game di kolom game_title, kode membuat prompt untuk mengidentifikasi apakah game dimainkan dalam mode "Pemain Tunggal", "Pemain Banyak", atau "Keduanya". Model menghasilkan jawaban yang kemudian dibersihkan dan divalidasi dengan memeriksa kata-kata kunci dalam hasilnya. Berdasarkan hasil ini, mode permainan dikategorikan dan ditambahkan ke dalam list mode_list. Setelah semua game diproses, kolom baru player_mode yang berisi informasi mode permainan dimasukkan ke dalam DataFrame.

In [9]:
mode_list = []

# Loop untuk setiap judul game dan mengambil mode permainan
for title in tqdm(df["game_title"]):
    # Prompt mode permainan
    prompt_mode = (
        f"Game berjudul '{title}' dimainkan dalam mode apa? "
        f"Pilih satu jawaban: Pemain Tunggal, Pemain Banyak, atau Keduanya."
    )

    mode_raw = generate_text(prompt_mode)

    # Validasi hasil mode
    mode_clean = mode_raw.lower()
    if "tunggal" in mode_clean and "banyak" not in mode_clean:
        mode = "Pemain Tunggal"
    elif "banyak" in mode_clean and "tunggal" not in mode_clean:
        mode = "Pemain Banyak"
    elif "tunggal" in mode_clean and "banyak" in mode_clean or "keduanya" in mode_clean:
        mode = "Keduanya"
    else:
        mode = "Tidak Diketahui"

    mode_list.append(mode)

# Gabungkan ke DataFrame sebagai kolom baru
df["player_mode"] = mode_list

 30%|███       | 15/50 [00:55<03:28,  5.96s/it]ERROR:tornado.access:500 POST /v1beta/models/gemini-2.0-flash-lite:generateContent?%24alt=json%3Benum-encoding%3Dint (127.0.0.1) 10926.22ms

Attempt 1 failed: 500 POST https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite:generateContent?%24alt=json%3Benum-encoding%3Dint: TypeError: Failed to fetch

100%|██████████| 50/50 [04:41<00:00,  5.62s/it]

In [10]:
df

,game_title,image_url,genre,short_description,player_mode
0,Street Fighter 6,https://images.igdb.com/igdb/image/upload/t_co...,Pertarungan,Street Fighter 6: Pertarungan jalanan klasik ...,Keduanya
1,Hunt: Showdown 1896,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Berburu monster brutal dan pem ain lain dalam ...,Keduanya
2,Wuthering Waves,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,Wuthering Waves adalah RPG aks i dunia terbuka...,Keduanya
3,Arma Reforger,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,Arma Reforger adalah game simu lasi perang mul...,Keduanya
4,Lethal Company,https://images.igdb.com/igdb/image/upload/t_co...,Horor,Lethal Company adalah game hor or kooperatif t...,Pemain Banyak
5,Arena Breakout: Infinite,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,"Masuki Arena Breakout: Infinit e, penembak FPS...",Pemain Banyak
6,Zenless Zone Zero,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,"""Zenless Zone Zero"" adalah gam e aksi RPG yang...",Pemain Tunggal
7,ARK: Survival Ascended,https://images.igdb.com/igdb/image/upload/t_co...,Bertahan,Bertahan hidup di dunia purba yang liar! Kump...,Keduanya
8,Sid Meier's Civilization VII,https://images.igdb.com/igdb/image/upload/t_co...,Strategi,Raih kejayaan dalam Civilizati on VII! Bangun ...,Keduanya
9,SMITE 2,https://images.igdb.com/igdb/image/upload/t_co...,MOBA,SMITE 2 adalah MOBA dewa-dewi generasi beriku...,Pemain Banyak
10,Throne and Liberty,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG,Jelajahi dunia terbuka yang lu as dalam **Thro...,Keduanya
11,Enshrouded,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,"Bangun, bertarung, dan jelajah i dunia yang di...",Keduanya
12,Poppy Playtime,https://images.igdb.com/igdb/image/upload/t_co...,Horor,"Jelajahi pabrik mainan terbeng kalai, pecahkan...",Keduanya
13,It Takes Two,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,Petualangan kooperatif yang me nakjubkan! Berm...,Pemain Banyak
14,DYNASTY WARRIORS: ORIGINS,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,Kalahkan ribuan musuh dalam pe rtempuran besar...,Keduanya
15,NHL 25,https://images.igdb.com/igdb/image/upload/t_co...,Olahraga,NHL 25: Rasakan aksi hoki es y ang otentik! Ku...,Keduanya
16,Balatro,https://images.igdb.com/igdb/image/upload/t_co...,Roguelike,Balatro adalah deckbuilder rog uelike tentang ...,Pemain Tunggal
17,MiSide,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,MiSide adalah game simulasi ke hidupan santai ...,Keduanya
18,Metaphor: ReFantazio,https://images.igdb.com/igdb/image/upload/t_co...,RPG,"Bertualanglah dalam Metaphor: ReFantazio, seb...",Pemain Tunggal
19,Indiana Jones and the Great Circle,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,"Sebagai Indiana Jones, pecahka n misteri kuno ...",Pemain Tunggal
20,Hell Let Loose,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Hell Let Loose adalah game pen embak taktis Pe...,Pemain Banyak
21,Super Mario 64,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,Petualangan 3D ikonik Mario! J elajahi dunia l...,Pemain Tunggal
22,S.T.A.L.K.E.R. 2: Heart of Chornobyl,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,"Bertahan hidup di Zona, dunia pasca-apokalipt...",Pemain Tunggal
23,STALCRAFT: X,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,STALCRAFT: X adalah RPG bertah an hidup multip...,Keduanya
24,Supermarket Together,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,Supermarket Together: Bekerja sama dengan tem...,Pemain Banyak
25,Ragnarok Online 2,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG,Ragnarok Online 2: Jelajahi du nia fantasi yan...,Pemain Banyak
26,The Outlast Trials,https://images.igdb.com/igdb/image/upload/t_co...,Horor,The Outlast Trials adalah game horor survival...,Pemain Banyak
27,Detroit: Become Human,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,"Dalam 'Detroit: Become Human', kendalikan and...",Pemain Tunggal
28,EA Sports UFC 2,https://images.igdb.com/igdb/image/upload/t_co...,Olahraga,Rasakan kerasnya pertarungan M MA! EA Sports U...,Keduanya
29,Palia,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,Palia adalah MMO komunitas yan g nyaman. Berin...,Pemain Banyak
30,Green Hell,https://images.igdb.com/igdb/image/upload/t_co...,Survival,Bertahan hidup di hutan Amazon yang kejam. Je...,Pemain Tunggal
31,Microsoft Flight Simulator 2024,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,Terbanglah di dunia yang detai l dalam Microso...,Keduanya
32,Teamfight Tactics,https://images.igdb.com/igdb/image/upload/t_co...,Strategi,Rakit tim juara dan lawan pema in lain dalam p...,Pemain Banyak
33,No Man's Sky,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,Jelajahi alam semesta yang tak terbatas di No...,Keduanya
34,Farming Simulator 25,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,Kembangkan pertanian impianmu di Farming Simu...,Keduanya
35,Tom Clancy's The Division 2,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Bertahan hidup di Washington D .C. pasca-pande...,Keduanya
36,Super Smash Bros. Ultimate,https://images.igdb.com/igdb/image/upload/t_co...,Pertarungan,Bertarunglah dengan berbagai k arakter ikonik ...,Keduanya
37,Dying Light,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,Bertahan hidup di dunia pasca- apokaliptik yan...,Keduanya
38,Sniper Elite: Resistance,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Sniper Elite: Resistance adala h game stealth ...,Keduanya
39,New World: Aeternum,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG,Jelajahi dunia Aeternum yang m emukau! Bertaru...,Keduanya
40,Hello Kitty Island Adventure,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,Jelajahi Pulau yang dipenuhi t eman Sanrio! Ke...,Pemain Tunggal
41,The Headliners,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,Pimpin band rockmu menuju punc ak! Kelola angg...,Pemain Banyak
42,Mir Tankov,https://images.igdb.com/igdb/image/upload/t_co...,Strategi,Mir Tankov adalah game aksi ta nk 3D intens. K...,Keduanya
43,The Binding of Isaac: Repentance,https://images.igdb.com/igdb/image/upload/t_co...,Roguelike,"""The Binding of Isaac: Repenta nce"" adalah *ro...",Pemain Tunggal
44,Exoborne,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Exoborne adalah open-world ext raction shooter...,Pemain Banyak
45,Grand Theft Auto: San Andreas,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,Jelajahi negara bagian San And reas yang luas ...,Keduanya
46,Infinity Nikki,https://images.igdb.com/igdb/image/upload/t_co...,Gaya,"Nikki memasuki dunia fantasi y ang luas, mengg...",Keduanya
47,Borderlands 3,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Tembak dan rampas habis-habisa n! Jelajahi dun...,Keduanya
48,Knight Online,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG,"Bertarung dalam Knight Online, MMORPG epik! P...",Pemain Banyak
49,Supermarket Simulator,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,"Kelola supermarket impianmu! B eli produk, tat...",Keduanya

## 5. Menyimpan dan download data yang sudah di tambahkan dengan format CSV

In [11]:
df.to_csv("game_data_enriched.csv", index=False)

# Unduh file hasilnya
files.download("game_data_enriched.csv")

In [195]:
import pandas as pd

# Ganti nama file sesuai file yang kamu upload
df = pd.read_csv("game_data_enriched.csv")

# Lihat 5 baris pertama untuk konfirmasi
df

,game_title,image_url,genre,desc,mode_permainan
0,Street Fighter 6,https://images.igdb.com/igdb/image/upload/t_co...,Pertarungan,Street Fighter 6: Hadirkan per tempuran jalana...,Keduanya
1,Hunt: Showdown 1896,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Berburu iblis di rawa Louisian a yang gelap. B...,Keduanya
2,Wuthering Waves,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,Jelajahi dunia terbuka luas ya ng dilanda benc...,Keduanya
3,Arma Reforger,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,'Arma Reforger' adalah game mi liter multiplay...,Keduanya
4,Lethal Company,https://images.igdb.com/igdb/image/upload/t_co...,Horor,Bertahan hidup sebagai pekerja kontrak korpor...,Pemain Banyak
5,Arena Breakout: Infinite,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,"Masuk ke dunia Arena Breakout: Infinite, game...",Pemain Banyak
6,Zenless Zone Zero,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,'Zenless Zone Zero' adalah RPG aksi cepat di ...,Keduanya
7,ARK: Survival Ascended,https://images.igdb.com/igdb/image/upload/t_co...,Bertahan,Bertahan hidup di dunia prasej arah! Jelajahi ...,Keduanya
8,Sid Meier's Civilization VII,https://images.igdb.com/igdb/image/upload/t_co...,Strategi,Bangun peradaban melalui waktu ! Kembangkan ko...,Keduanya
9,SMITE 2,https://images.igdb.com/igdb/image/upload/t_co...,MOBA,"SMITE 2 adalah MOBA dewa-dewi, bertempur dala...",Pemain Banyak
10,Throne and Liberty,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG,Throne and Liberty adalah MMOR PG dunia terbuk...,Pemain Banyak
11,Enshrouded,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,"Bangun, bertahan hidup, dan ta klukkan dunia y...",Keduanya
12,Poppy Playtime,https://images.igdb.com/igdb/image/upload/t_co...,Horor,"Jelajahi pabrik mainan terbeng kalai, pecahkan...",Keduanya
13,It Takes Two,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,Petualangan kooperatif yang me ngharukan di ma...,Pemain Banyak
14,DYNASTY WARRIORS: ORIGINS,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,Bertempurlah di medan perang l uas sebagai jen...,Keduanya
15,NHL 25,https://images.igdb.com/igdb/image/upload/t_co...,Olahraga,NHL 25: Rasakan serunya hoki e s! Kuasai keahl...,Keduanya
16,Balatro,https://images.igdb.com/igdb/image/upload/t_co...,Roguelike,Balatro adalah deckbuilder rog uelike tentang ...,Pemain Tunggal
17,MiSide,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,MiSide adalah game simulasi sa ntai di mana ka...,Keduanya
18,Metaphor: ReFantazio,https://images.igdb.com/igdb/image/upload/t_co...,RPG,"Dalam 'Metaphor: ReFantazio', jelajahi dunia ...",Pemain Tunggal
19,Indiana Jones and the Great Circle,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,"Menjadi Indiana Jones, jelajah i dunia, pecahk...",Pemain Tunggal
20,Hell Let Loose,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Hell Let Loose adalah game pen embak orang per...,Pemain Banyak
21,Super Mario 64,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,Petualangan 3D klasik Mario! J elajahi dunia l...,Pemain Tunggal
22,S.T.A.L.K.E.R. 2: Heart of Chornobyl,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Masuklah ke zona Chernobyl yan g mematikan! Be...,Pemain Tunggal
23,STALCRAFT: X,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,STALCRAFT: X adalah game berta han hidup MMO b...,Pemain Banyak
24,Supermarket Together,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,Bekerja sama dengan teman dala m game 'Superma...,Pemain Banyak
25,Ragnarok Online 2,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG,Ragnarok Online 2 adalah MMORP G penuh aksi de...,Pemain Banyak
26,The Outlast Trials,https://images.igdb.com/igdb/image/upload/t_co...,Horor,Bertahan hidup dalam uji coba psikologis yang...,Pemain Banyak
27,Detroit: Become Human,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,"Dalam Detroit: Become Human, k endalikan andro...",Pemain Tunggal
28,EA Sports UFC 2,https://images.igdb.com/igdb/image/upload/t_co...,Pertarungan,Rasakan kerasnya pertarungan d i EA Sports UFC...,Keduanya
29,Palia,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,"Palia adalah MMO komunitas yan g ramah, tempat...",Pemain Banyak
30,Green Hell,https://images.igdb.com/igdb/image/upload/t_co...,Survival,Bertahan hidup sendirian di hu tan Amazon yang...,Keduanya
31,Microsoft Flight Simulator 2024,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,Terbanglah di dunia nyata dala m **Microsoft F...,Keduanya
32,Teamfight Tactics,https://images.igdb.com/igdb/image/upload/t_co...,N,"Rancang dan atur tim pahlawan unik, kombinasi...",Pemain Banyak
33,No Man's Sky,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,"Jelajahi galaksi tak terbatas! Dalam ""No Man'...",Keduanya
34,Farming Simulator 25,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,Kembangkan pertanian impian An da di Farming S...,Keduanya
35,Tom Clancy's The Division 2,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Division 2: Bertahan hidup di Washington D.C....,Keduanya
36,Super Smash Bros. Ultimate,https://images.igdb.com/igdb/image/upload/t_co...,Pertarungan,Pertarungan crossover epik! Pi lih dari roster...,Keduanya
37,Dying Light,https://images.igdb.com/igdb/image/upload/t_co...,Horor,Bertahan hidup di dunia pasca- apokaliptik yan...,Tidak Diketahui
38,Sniper Elite: Resistance,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Tembak dan sembunyi dalam Snip er Elite: Resis...,Tidak Diketahui
39,New World: Aeternum,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG,"Jelajahi dunia Aeternum yang m istis dalam ""Ne...",Tidak Diketahui
40,Hello Kitty Island Adventure,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,Berteman dengan Hello Kitty da n teman-temanny...,Tidak Diketahui
41,The Headliners,https://images.igdb.com/igdb/image/upload/t_co...,Petualangan,Menangkan kompetisi headline b erita! Sebagai ...,Keduanya
42,Mir Tankov,https://images.igdb.com/igdb/image/upload/t_co...,Strategi,Kendalikan tank kuat dalam per tempuran PvP ya...,Keduanya
43,The Binding of Isaac: Repentance,https://images.igdb.com/igdb/image/upload/t_co...,Roguelike,Ekspedisi roguelike mengerikan di dunia gelap...,Pemain Tunggal
44,Exoborne,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Exoborne adalah game survival open-world PvPv...,Keduanya
45,Grand Theft Auto: San Andreas,https://images.igdb.com/igdb/image/upload/t_co...,Aksi,Jelajahi negara bagian San And reas sebagai Ca...,Keduanya
46,Infinity Nikki,https://images.igdb.com/igdb/image/upload/t_co...,Gaya,Dandani Nikki dalam ribuan pak aian mempesona!...,Keduanya
47,Borderlands 3,https://images.igdb.com/igdb/image/upload/t_co...,Shooter,Tembak dan rampas dalam Border lands 3! Sebaga...,Keduanya
48,Knight Online,https://images.igdb.com/igdb/image/upload/t_co...,MMORPG,"Masuki dunia fantasi di Knight Online, game M...",Pemain Banyak
49,Supermarket Simulator,https://images.igdb.com/igdb/image/upload/t_co...,Simulasi,"Kelola supermarket impianmu! S usun rak, isi p...",Keduanya